# Generated by Django 4.2.27 on 2025-12-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_amenity_icon_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='room',
            name='type',
        ),
        migrations.AddField(
            model_name='room',
            name='service',
            field=models.ForeignKey(default=1, limit_choices_to={'category': 'accommodation'}, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.service'),
        ),
    ]
